# Generated by Django 4.2.6 on 2023-11-18 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(name="todo", order_with_respect_to="user",),
    ]
